import type { Metadata } from "next";
import "./globals.css";
import Header from "@/src/components/Header";

export const metadata: Metadata = {
	title: "Store",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Header />
				<main className="flex-1">{children}</main>
			</body>
		</html>
	);
}
