import type { Metadata } from "next";
import "./globals.css";
import Header from "@/src/components/Header";
import ReactQueryProvider from "@/src/components/ReactQueryProvider";

export const metadata: Metadata = {
	title: "Store",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<Header />
				<ReactQueryProvider>
					<main className="flex-1">{children}</main>
				</ReactQueryProvider>
			</body>
		</html>
	);
}
